### ISSUE TITLE
"Fill TOTP" does nothing on Firefox 61b

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc-browser#161]
Since the latest release of the extension (as of May 2018) I think there's a regression on the Fill OTP on Firefox, the code is not generated. At this time only noticed when logging on Github.
It works on Chromium and it worked on Firefox.

## Expected Behavior
The OTP generation should generate a token like it did before

## Current Behavior
During the OTP auth pahse, the OTP generation fails and the keepassxc icon shows a (non-selectable) confirmation of the credentials (see attached image)

## Steps to Reproduce (for bugs)
- Sign in on gihub
- keepassxc correctly autofills user+pass
- next step ORP, keepassxc does not produce the TOTP. Shows a  a (non-selectable) confirmation of the credentials.

## Debug info
KeePassXC-Browser Version: 1.1.3
KeePassXC Version: 2.3.3 
Operating system: Ubuntu 18.04, x86_64
Browser: Firefox only, Chromium is ok
Proxy used: YES

**Comment by varjolintu** [comment]
Found the bug. It's fixed in the next release.

Details: the credential ID wasn't saved outside the content script. This means that if page was reloaded or there's a separate page for TOTP the value was forgotten.

**Comment by apiraino** [comment]
That's great! Thank you so much for squashing the bug this fast :-)

**Comment by apiraino** [comment]
Downloaded the latest and it works! thank you

**Comment by jstnchristian** [comment]
I am still having this issue in Firefox 62.0, using KeepassXC-Browser 1.20. Should I file a new issue?
