### ISSUE TITLE
Login with Handy-Signatur (Austria)

### ISSUE THREAD

**Issue by h-h-** [keepassxreboot/keepassxc-browser#1740]
## Summary
I want to login to web pages with KeePassXC and KeePassXC-Browser on Firefox at pages which use the austrian Handy-Signatur.
But the login and password fields are not detected.

## Examples
Visit [https://www.gesundheit.gv.at/](https://www.gesundheit.gv.at/).
Click "Login" on the top right.
Click "Handy" (near "zum Login mittels Handysignatur")
Now the fields "username/mobile phone number" and "Signature password" should be filled by KeePassXC-Browser.

There are some other sites where to login with Handy-Signatur. The issue exists on all sites I know so far.

**Comment by varjolintu** [comment]
A tricky one. There's an iframe and even the context menu fill doesn't seem to handle it correctly (`activeElement` is `iframe` instead of input field).

**Comment by profiluefter** [comment]
have to say that this has worked for me for years and I just confirmed it still working

**Comment by h-h-** [comment]
> 

On which OS and browser is it working? The issue occurs on Win10 Pro 21H2, latest Firefox 106.0.2 (64-bit)

**Comment by profiluefter** [comment]
@h-h- 
I have it working on Win10 Home 22H2 (just updated recently though, worked before), also latest Firefox 106.0.2 (64-bit)
KeePassXC 2.7.3 (it's a bit tedious because of #1751 which was just fixed, but before that bug it also worked) with Extension 1.8.3
so probably the same as you

I have the URL "https://a-trust.at" as main url and "https://handy-signatur.at" as additional url and my phone number as username and the password as password. Haven't done any specific changes or something, it just worked out of the box like that.

**Comment by h-h-** [comment]
@profiluefter: Thanks for the hints. After adding https://a-trust.at/ as additional URL it worked.
I could have found this out by myself by just inspecting the network traffic. Shame on me.

**Comment by h-h-** [comment]
@varjolintu If you still think this can be solved with browser integration for either https://www.gesundheit.gv.at/ or https://sso.gesundheit.gv.at (what the normal user sees in the address bar), then please reopen this issue.

**Comment by profiluefter** [comment]
Just tried it and it doesn't work for me either. However, if you click the "Separate window" button it does work in the new window. (Assuming you add `https://service.a-trust.at` to the URLs)

I had a quick look using the debug logs. It is hitting this code path:

https://github.com/keepassxreboot/keepassxc-browser/blob/63d929092db6d836970b0b642297f53a3863a330/keepassxc-browser/content/keepassxc-browser.js#L1027-L1044

```
[Debug keepassxc-browser.js:598] KeePassXC-Browser - Error: Credential request ignored from another domain: service.a-trust.at
[Debug keepassxc-browser.js:637] KeePassXC-Browser - Error: Credential request ignored from another domain: service.a-trust.at
[Debug username-field.js:168] KeePassXC-Browser - Error: Credential list is empty for: https://service.a-trust.at/
[Debug fill.js:204] KeePassXC-Browser - Fehler:
Keine Anmeldungen gefunden. https://service.a-trust.at/
```

I did try enabling the cross origin iframes in the addon options however it did not change anything:

![grafik](https://github.com/keepassxreboot/keepassxc-browser/assets/18028031/6c53adb5-abc9-482f-b5d8-2916c06deeaa)

**Comment by c1ean3r** [comment]
That drives me crazy, the only login I use a lot but unfortunately still doesn't work

**Comment by varjolintu** [comment]
With https://www.gesundheit.gv.at/ -> Login -> ID Austria it works for me when I have an entry with `https://service.a-trust.at` set as the URL. To Site Preferences `https://eid.oesterreich.gv.at/authHandler/public/secure/auth/start` is added with _Allow Cross-Origin frames" enabled.

Similar approach should work all sites using the A Trust login.

**Comment by c1ean3r** [comment]
Thanks for the quick feedback! I tried this, but it still doesn´t work for me:

![grafik](https://github.com/user-attachments/assets/cd76fbf3-c6bf-4f44-8349-8a1067a99d79)

URL `https://service.a-trust.at` is added with Login entry in KeePassXC 2.7.9.

Allow Cross-Origin frame enabled:

![grafik](https://github.com/user-attachments/assets/f97c1d6a-a5b4-44c4-bdee-c3988a1078b2)

KeePassXC and browser have been restarted, no change.
Perhaps I am missing another setting?

**Comment by varjolintu** [comment]
@c1ean3r Check your entry's properties, especially the Plugin Data section. Is there a deny permission set for the site?

**Comment by c1ean3r** [comment]
> @c1ean3r Check your entry's properties, especially the Plugin Data section. Is there a deny permission set for the site?

No deny permission. I have even created a fresh entry, same issue.

**Comment by varjolintu** [comment]
> > @c1ean3r Check your entry's properties, especially the Plugin Data section. Is there a deny permission set for the site?
> 
> No deny permission. I have even created a fresh entry, same issue.

Try to adjust the Site Preferences URL then? Maybe it doesn't detect the iframe allowance properly.

**Comment by c1ean3r** [comment]
> Try to adjust the Site Preferences URL then? Maybe it doesn't detect the iframe allowance properly.

Thanks for that hint - after a few tests with different URLs it finally works now. I had to shorten the url to `https://eid.oesterreich.gv.at`
