### ISSUE TITLE
Cross-origin iframes option not working flawlessly

### ISSUE THREAD

**Issue by TobyC5** [keepassxreboot/keepassxc-browser#2170]
The cross-origin iframes option is not working correctly - although I have added the URL in settings and allowed cross-origin iframes.

## Expected Behavior
Being able to fill in the password via KeePassXC button in the password field without switching to another tab to make it work.

## Current Behavior
Error message appears when you click on the KeePassXC button in the password field (in German for me): "Fehler: Keine Anmeldungen gefunden. https://anmelden.check24.de".
If you switch to another browser tab and back and click on the button again, then it works.

## Steps to Reproduce (for bugs)
Please watch the following screen recording: https://github.com/keepassxreboot/keepassxc-browser/assets/117075837/8af0f776-017b-41be-aa35-132e101fd38d
1. Go to https://kundenbereich.check24.de/user/points.html
2. Click on "jetzt anmelden"
3. Click on the KeePassXC button in the password field. Error message appears.
4. Switch to another browser tab.
5. Go back to the original browser tab.
6. Click on the KeePassXC button in the password field again. Now password is filled in.

## Debug info
No browser's JavaScript console messages and errors...
KeePassXC - 2.8.0-snapshot
KeePassXC-Browser - 1.9.0.3
Operating system: Win64
Browser: Mozilla Firefox 124.0

**Comment by varjolintu** [comment]
Possible already fixed in https://github.com/keepassxreboot/keepassxc-browser/pull/2166

**Comment by varjolintu** [comment]
Add `https://anmelden.check24.de/*` to Site Preferences and enable _Username-Only Detection_ and _Allow Cross-Origin iframes_ options.

**Comment by TobyC5** [comment]
Hi @varjolintu, in my video you can see it's already added at the bottom. Still, it does not work for me.

**Comment by TobyC5** [comment]
The problem is still there with 1.9.1 so it seems to be unrelated to https://github.com/keepassxreboot/keepassxc-browser/pull/2166.

**Comment by varjolintu** [comment]
Try adding `https://kundenbereich.check24.de/index.html` to Site Preferences list and enable the _Allow Cross-Origin iframes_  for it.

**Comment by TobyC5** [comment]
Still the same error. I need to switch the tab and go back and only then it works.

**Comment by varjolintu** [comment]
I tested this a bit further and found one bug which has slipped through.

**Comment by TobyC5** [comment]
I can confirm it's working now. Thanks!
