### ISSUE TITLE
Settings: Connected databases screen has confusing caption ("Les bases de données KeePassXC suivantes...")

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2231]
The connected databases settings tab of the extension is confusing in French due to the following message:

> Les bases de données KeePassXC suivantes sont connectées à KeePassXC-Browser.

This message displays **below** the table it refers to, as can be seen in the following screenshot :
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/486141/f14340e2-d62f-479b-9938-ce738678d7a0)

This was fixed for English in bfabd6c, but [visibly still affects quite a few languages](https://github.com/search?q=repo%3Akeepassxreboot/keepassxc-browser%20%22optionsConnectedDatabasesText%22&type=code).

## Cause
This must have been a regression when upgrading from Bootstrap 3 to Bootstrap 4+.

## Possible Solution
[Bootstrap 5 added a class which allows to avoid this.](https://stackoverflow.com/a/48648073/5405434) However, the original phrasing was not a _caption_ per se, and could simply be outside the table element.

## Debug info
KeePassXC-Browser - 1.9.0.5
Browser: Firefox

**Comment by varjolintu** [comment]
As said before, language specific issues are solved in Transifex side. No need to make separate issues here.

**Comment by Chealer** [comment]
Thank you @varjolintu but can you clarify how this was solved? You let the code unchanged but fixed the message in the affected languages?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/issues/2220#issuecomment-2155223315

**Comment by Chealer** [comment]
This persists in 1.9.7. @varjolintu : In which version should this be solved?

**Comment by varjolintu** [comment]
> This persists in 1.9.7. [@varjolintu](https://github.com/varjolintu) : In which version should this be solved?

This issue persist as long as it has not been translated correctly in Transifex. There's nothing I can do about it.
