### ISSUE TITLE
Portable mode upgrade breaks integration until I fix the registry key

### ISSUE THREAD

**Issue by Henry78** [keepassxreboot/keepassxc-browser#456]
## Expected Behavior
Everything works after replacing the last version of the KeePassXC portable with the current.

## Current Behavior
After upgrading to 2.4 (portable) I wasn't able to connect to KeePassXC from the browser extension. I tried a lot of things, even cleared all settings.
Following the Troubleshooting guide, I ...

## Possible Solution
... discovered that the registry key still pointed to the old KeePass-XC directory (...2.3.6-...). I fixed the key (...2.4.0-...) and everything works again.

Please update the registry key to the current installation directory or provide some information for the poor portable users, that the reg key needs to be manually adjusted.

**Comment by varjolintu** [comment]
This needs to be tested if disabling and re-enabling the browser support is a workaround for this. Of course the registry keys should be updated when necessary.

**Comment by Henry78** [comment]
> disabling and re-enabling the browser support

I tested this without success (before I found the outdated reg key). I removed all connected browsers from the database settings and disabled the integration at the KeePassXC settings, removed the browser extension.

After that i enabled/configured everything as documented with a new database. Without success. The moment I fixed the key, I restarted FF and KPXC and everthing works as exepected.

**Comment by varjolintu** [comment]
Good to know. Thanks for testing it out!

**Comment by menghuu** [comment]
Hi, how to find the registry key? I rename the older keepassxc portable dir and I found it broken, so I remove all files and reinstall keepassxc 2.4.1.msi, it not works and reinstall keepassxc 2.4.0.msi, it still not works.
so, where is the registry key?

**Comment by menghuu** [comment]
I may find the registry key location. They are in `HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\` , if firefox, it may in `xxx\Mozilla\Firefox\NativeMessageingHosts\`

since I have already delete the `org.keepassxc.keepassxc_browser_xxxxx.json`, delete the keepassxc browser addon configuration Databases and I reinstall with `.msi`(currently 2.4.0), so I cut the `deleted` json into install dir (also change the proxy.exe file path), and change the registry key above, it seems do not work.
