### ISSUE TITLE
Redetect credential fields when fill username and password is clicked

### ISSUE THREAD

**Issue by zroug** [keepassxreboot/keepassxc-browser#538]
## Expected Behavior
When the user clicks fill username and password from the right click menu and no credential fields are detected yet, KeePassXC-Browser should redetect the credential fields before filling username and password.

## Current Behavior
When the user clicks fill username and password and the credential fields aren't detected yet, nothing happens. This can be confusing because the user clearly sees the credential fields because he has right clicked on them.

## Steps to Reproduce (for bugs)
1. Go to a page where the credential fields only appear after you have clicked on something.
2. Right click -> Fill username and password.
3. Nothing happens.

## Debug info
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
This is possible fixed with: https://github.com/keepassxreboot/keepassxc-browser/pull/520. Wait for the next version.

In the meawhile, what is the site that triggers this bug?

**Comment by zroug** [comment]
Oh thats cool. One site for which I know that the error occurs is https://cronometer.com/.

**Comment by varjolintu** [comment]
Please check if the latest version 1.4.4 fixes the issue.

**Comment by zroug** [comment]
No, 1.4.4 didn't fix the issue. Right click -> KeePassXC-Browser -> Fill username and password still only works after I have clicked redetect credential fields manually. (On the site that I have mentioned.)

**Comment by varjolintu** [comment]
Seems like this is a Firefox issue. Chromium-based browsers work just fine.

**Comment by varjolintu** [comment]
#351 fixes this one too.
